### ISSUE TITLE
Illegal offset type - QuoteHandler

### ISSUE THREAD

**Issue by saigadekar** [magestat/magento2-split-order#24] opened 2019-05-28 16:23 UTC
Magento Version:
"magento/product-community-edition": "2.3.1"

 > main.CRITICAL: Warning: Illegal offset type in app/code/Magestat/SplitOrder/Model/QuoteHandler.php on line 77 {"exception":"[object] 

Function : - 
```php
    public function normalizeQuotes($quote)
    {
        // if module is active.
        if (!$this->helperData->isActive()) {
            return false;
        }
        $attributes = $this->helperData->getAttributes();
        if (empty($attributes)) {
            return false;
        }

        $groups = [];
        foreach ($quote->getAllVisibleItems() as $item) {
            $product = $item->getProduct();

            $attribute = $this->getProductAttributes($product, $attributes);
            if (empty($attribute)) {
                // Kill function if attribute is null.
                return false;
            }
            $groups[$attribute][] = $item;  ///this is the where the error is thrown - line 77
        }
        // If order have more than one item.
        if (count($groups) > 1) {
            return $groups;
        }
        return false;
    }
```
I have selected product attribute as  Quantity in config to split the order even though the products are instock and even though i have added only one product i am getting this error and order doesn't get placed.

any help will be  great.

**Comment by williankeller** [comment] 2019-05-29 09:28
Hi @saigadekar, could you please paste the full error message and describe where (which screen) the error shows up?

**Comment by binnykumar** [comment] 2019-05-29 13:15
Hi @saigadekar , i faced this issue also.

Replace : 
            
$groups[$attribute][] = $item;

With : 

$attribute            = 'item_'. $attribute;
$groups[$attribute][] = $item;

This will fix your issue.

**Comment by williankeller** [comment] 2019-05-29 15:01
Hi @binnykumar, this is not the right solution, this way you're forcing the conversion of an object to a string. This way you will always get the same attribute, response wrong response.
Please refer this commit with the real fix https://github.com/magestat/magento2-split-order/pull/25/commits/bd210d74b90f0c9908d90d89fbf56bc81925f993.
This issue will be closed as soon the PR is merged.

**Comment by binnykumar** [comment] 2019-05-30 04:36
Hi @williankeller , thanks for the advice.

**Comment by saigadekar** [comment] 2019-05-30 10:40
hi @williankeller 

after adding the fix above error got cleared but now m  getting this error on success page. I tried a single product and also multiple product (1 stock and 1 outofstock product (backorder allowed one))
1 exception(s):
Exception #0 (Exception): Warning: count(): Parameter must be an array or an object that implements Countable i app/code/Magestat/SplitOrder/Block/Checkout/Success.php on line 70

  public function getOrderArray()
    {
        $splittedOrders = $this->checkoutSession->getOrderIds();
        // Remove session.
        $this->checkoutSession->unsOrderIds();

        // If number of orders is just like one, kill function.
        if (count($splittedOrders) <= 1) { //line 70
            return false;
        }
        // Return prepared block data.
        return $splittedOrders;
    }

**Comment by williankeller** [comment] 2019-05-31 06:18
Closing by fix released: https://github.com/magestat/magento2-split-order/pull/25

**Closed by williankeller** 2019-05-31 06:18 UTC
Labels: bug

**Comment by williankeller** [comment] 2019-05-31 06:21
@saigadekar,
> Even if there are two products (1 instock and 1 outofstock) selected Both product attribute are showing out of stock
> which makes group count to 1 and further it fails because checkout session is not getting set.

Did you have executed reindex after applied the stock changes? The selection returns the product attribute value. Please make sure your product is returning _In_ and _Out_ of stock properly.

**Comment by binnykumar** [comment] 2019-05-31 09:25
@saigadekar , 

yes you can fix this issue by updating this line :
Block/Checkout/Success.php 

Look for 

if (count($splittedOrders) <= 1) {
            return false;
}

And replace it with 

if (is_array($splittedOrders) && count($splittedOrders) <= 1) {
            return false;
}

> hi @williankeller
> 
> after adding the fix above error got cleared but now m getting this error on success page. I tried a single product and also multiple product (1 stock and 1 outofstock product (backorder allowed one))
> 1 exception(s):
> Exception #0 (Exception): Warning: count(): Parameter must be an array or an object that implements Countable i app/code/Magestat/SplitOrder/Block/Checkout/Success.php on line 70
> 
> Even if there are two products (1 instock and 1 outofstock) selected Both product attribute are showing out of stock
> **QuoteHandler.php**
> `$attribute = $this->getProductAttributes($product, $attributes); // this returns out of stock`
> 
> which makes group count to 1 and further it fails because checkout session is not getting set.

**Comment by saigadekar** [comment] 2019-05-31 13:29
@williankeller - I did reindex and even created a new product but still its returning outofstock as the frontend value and suppose if i try to use another attribute (country_of_manufacture ) this returns me empty value - i have update the data in product and also executed the reindex.

**Comment by williankeller** [comment] 2019-05-31 13:32
@binnykumar - You can't use `is_array($splittedOrders)` the right way is to validate if this variable is an empty and _or_ condition.

**Comment by williankeller** [comment] 2019-05-31 13:40
@saigadekar, @binnykumar 
Please refer the Pull Request https://github.com/magestat/magento2-split-order/pull/27, we did some improvements to make sure the stock is returning the expected value base on the _Quantity_ attribute.
Now you're able to select some options including backorder configuration.
![image](https://user-images.githubusercontent.com/2963928/58709250-0efb0b80-83ba-11e9-95b0-82e1beb74d1c.png)
This Pull Request will be merged and a new release will be generated soon.

**Comment by saigadekar** [comment] 2019-05-31 15:09
Hi @williankeller 

Thanks for the help . i Have merged this on my local code and configured it according but now its returing "in" for both the products - product which is having less then zero saleable qty and also for product which is instock.

Please note the backorder feature which is activated is only at product level. meaning only selected products will be allowed for backorder.

**Comment by williankeller** [comment] 2019-05-31 15:12
@saigadekar - You have to enable the backorder option or set one of the products to out of stock

**Comment by saigadekar** [comment] 2019-05-31 16:04
@williankeller - have set the Product to backorder in product edit section and saleable qty in listing is in negative and yet its showing in stock when returning and i even tried Type of Stock Attribute => Stock Quantity (Inventory value) even there its returning the qty but i need  saleable qty . I will try to check this in production mode on n will see its giving me correct results then

**Comment by williankeller** [comment] 2019-05-31 18:13
@saigadekar,
Unfortunately, it's not possible by using saleable qty. You have to complete the order until the last step to have the value decreased from the inventory.

**Comment by williankeller** [comment] 2019-05-31 18:23
I'm not able to reproduce it by following the default flow.
Configuration:
![image](https://user-images.githubusercontent.com/2963928/58726308-b2abe200-83e1-11e9-9df2-2d199ec8e18e.png)

One of my products is "In Stock" with zero qty:
![image](https://user-images.githubusercontent.com/2963928/58726352-cfe0b080-83e1-11e9-8b54-86928cfa5dfc.png)

Another product has more than 500 items in stock.
I got 2 orders in the end. One to the out of stock and one to in-stock items.

**Comment by williankeller** [comment] 2019-05-31 18:29
@saigadekar
If your product has less than 1 item and stock and you have enabled the backorder configuration under the Magestat module, you should enter in this condition: https://github.com/magestat/magento2-split-order/blob/develop/Model/ExtensionAttributes.php#L60

If you're expecting the value being loaded from the saleable quantity, unfortunately, it's not possible.

**Comment by saigadekar** [comment] 2019-06-03 05:35
@williankeller 

Problem which i am facing is my stock qty is not getting reduced when back order is enabled hence its not going in out of stock condition. but the saleable qty which is shown in listing is getting reduced.

**Comment by saigadekar** [comment] 2019-06-03 10:33
@williankeller 

i added below code in ExtensionAttributes.php -   quantityAndStockStatus function.

         use Magento\InventorySalesAdminUi\Model\GetSalableQuantityDataBySku;
         $this->getSalableQuantityDataBySku = $getSalableQuantityDataBySku;
         $salable = $this->getSalableQuantityDataBySku->execute($sku);
        
        if($this->helperData->getBackorder() && $salable[0]['qty'] < 0){
            return 'out';
        }

**Comment by saigadekar** [comment] 2019-06-05 11:15
@williankeller 

Order is splitting but there is a currency conversion issue - 
Please check the raised issue
https://github.com/magestat/magento2-split-order/issues/30

Thanks,
